/* DO NOT EDIT THIS FILE - it is machine generated */
#include "cn_stu_cusview_ruiz_jnidemo2_JniTest2Util.h"

/*
 * Class:     cn_stu_cusview_ruiz_jnidemo2_JniTest2Util
 * Method:    greetFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_stu_cusview_ruiz_jnidemo2_JniTest2Util_greetFromJni
  (JNIEnv *env, jobject){

    return env-> NewStringUTF("Hello Java! This is jni.");

  }

