/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_stu_cusview_ruiz_jnidemo2_JniTest2Util */

#ifndef _Included_cn_stu_cusview_ruiz_jnidemo2_JniTest2Util
#define _Included_cn_stu_cusview_ruiz_jnidemo2_JniTest2Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_stu_cusview_ruiz_jnidemo2_JniTest2Util
 * Method:    greetFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_stu_cusview_ruiz_jnidemo2_JniTest2Util_greetFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
